services:
  - type: web
    name: cipherecore-web
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: SITE_URL
        value: https://cipherecore-web.onrender.com
        scope: run_time
      - key: NODE_ENV
        value: production
        scope: run_time
      - key: PORT
        value: 3000
        scope: run_time
